list: $/shohabbos/bigbluebutton/models/meeting/columns.yaml
modelClass: Shohabbos\Bigbluebutton\Models\Meeting
title: Meetings
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
